/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'Project_52367' 
 * Target:  'HT32' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ht32f5xxxx_01.h"



#endif /* RTE_COMPONENTS_H */
